name: Deploy to Vercel

# on:
#   push:
#     branches:
#       - main  # Tự động chạy khi có thay đổi trên nhánh main
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: ${{github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Phiên bản Node.js mà dự án sử dụng
      - name: Install Yarn
        run: npm install --global yarn@1

      - name: Install dependencies
        run: yarn # Cài đặt các phụ thuộc

      - name: Build the project
        run: yarn build # Build dự án

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
